version: '3.7'
services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      - jenkins-network
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "3000:3000"
      - "5000:5000"
      - "2376:2376"

  jenkins-blueocean:
    build:
      context: ./
      dockerfile: Dockerfile-jenkins-bo
    networks:
      - jenkins-network
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins-network:
    external: true
    name: jenkins-network

volumes:
  jenkins-docker-certs:
  jenkins-data:
